trying setting external variables

diff --git a/.github/workflows/test-runtime.yaml b/.github/workflows/test-runtime.yaml
--- a/.github/workflows/test-runtime.yaml
+++ b/.github/workflows/test-runtime.yaml
@@ -16,10 +16,20 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Docker build and test
+        id: build_and_test
         run: |
           cd Docker
           python3 docker-netmeld.py tester > Dockerfile \
             && docker build --no-cache --tag "netmeld-tester" . \
             && rm Dockerfile
-          docker run --rm -t netmeld-tester || exit 1
+          docker run --rm -t netmeld-tester
+          echo "::set-output name=failures::$?"
           docker image rm netmeld-tester
+
+
+      - name: Check for failing tests
+        if: ${{ steps.build_and_test.outputs.failures != 0 }}
+        uses: actions/github-script@v7
+        with:
+          script: |
+            core.setFailed('Some tests failed')
